name       : mjpegtools
version    : 2.2.0
release    : 4
source     :
    - https://sourceforge.net/projects/mjpeg/files/mjpegtools/2.2.0/mjpegtools-2.2.0.tar.bz2 : a84349839471052db1ef691134aacf905b314dfce8762d47e10edcc9ab5f97d8
license    : GPL-2.0-or-later
component  :
    - multimedia.codecs
    - libs : programming.library
summary    :
    - MJPEG conversion tools
    - libs : mjpegtools libraries
description: |
    The mjpeg programs are a set of tools that can do recording of videos and playback, simple cut-and-paste editing and the MPEG compression of audio and video under Linux.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libdv)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(sdl)
    - pkgconfig(x11)
setup      : |
    %patch -p1 < $pkgfiles/0001-videodev2-the-vengeance.patch
    %reconfigure --disable-static \
                 --enable-largefile
build      : |
    %make
install    : |
    %make_install
patterns   :
    - libs : /usr/lib64/lib*.so.*
