name       : mjpegtools
version    : 2.2.1
release    : 5
source     :
    - https://sourceforge.net/projects/mjpeg/files/mjpegtools/2.2.1/mjpegtools-2.2.1.tar.gz/download : b180536d7d9960b05e0023a197b00dcb100929a49aab71d19d55f4a1b210f49a
license    : GPL-2.0-or-later
component  :
    - multimedia.codecs
    - libs : programming.library
summary    :
    - MJPEG conversion tools
    - libs : mjpegtools libraries
description: |
    The mjpeg programs are a set of tools that can do recording of videos and playback, simple cut-and-paste editing and the MPEG compression of audio and video under Linux.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libdv)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libv4l2)
    - pkgconfig(sdl)
    - pkgconfig(x11)
setup      : |
    %patch -p1 < $pkgfiles/0001-videodev2-the-vengeance.patch
    %reconfigure --disable-static \
                 --enable-largefile
build      : |
    %make
install    : |
    %make_install
patterns   :
    - libs : /usr/lib64/lib*.so.*
